In [1]:
import numpy as np
import time
import cv2
import math

In [2]:
labelsPath = "./coco.names"
LABELS = open(labelsPath).read().strip().split("\n")
LABELS

['person',
 'bicycle',
 'car',
 'motorcycle',
 'airplane',
 'bus',
 'train',
 'truck',
 'boat',
 'traffic light',
 'fire hydrant',
 'stop sign',
 'parking meter',
 'bench',
 'bird',
 'cat',
 'dog',
 'horse',
 'sheep',
 'cow',
 'elephant',
 'bear',
 'zebra',
 'giraffe',
 'backpack',
 'umbrella',
 'handbag',
 'tie',
 'suitcase',
 'frisbee',
 'skis',
 'snowboard',
 'sports ball',
 'kite',
 'baseball bat',
 'baseball glove',
 'skateboard',
 'surfboard',
 'tennis racket',
 'bottle',
 'wine glass',
 'cup',
 'fork',
 'knife',
 'spoon',
 'bowl',
 'banana',
 'apple',
 'sandwich',
 'orange',
 'broccoli',
 'carrot',
 'hot dog',
 'pizza',
 'donut',
 'cake',
 'chair',
 'couch',
 'potted plant',
 'bed',
 'dining table',
 'toilet',
 'tv',
 'laptop',
 'mouse',
 'remote',
 'keyboard',
 'cell phone',
 'microwave',
 'oven',
 'toaster',
 'sink',
 'refrigerator',
 'book',
 'clock',
 'vase',
 'scissors',
 'teddy bear',
 'hair drier',
 'toothbrush']

In [3]:
np.random.seed(42)
COLORS = np.random.randint(0, 255, size = (len(LABELS), 3), dtype = 'uint8')
COLORS

array([[102, 220, 225],
       [ 95, 179,  61],
       [234, 203,  92],
       [  3,  98, 243],
       [ 14, 149, 245],
       [ 46, 106, 244],
       [ 99, 187,  71],
       [212, 153, 199],
       [188, 174,  65],
       [153,  20,  44],
       [203, 152, 102],
       [214, 240,  39],
       [121,  24,  34],
       [114, 210,  65],
       [239,  39, 214],
       [244, 151,  25],
       [ 74, 145, 222],
       [ 14, 202,  85],
       [145, 117,  87],
       [184, 189, 221],
       [116, 237, 109],
       [ 85,  99, 172],
       [226, 153, 103],
       [235, 146,  36],
       [151,  62,  68],
       [181, 130, 160],
       [160, 166, 149],
       [  6,  69,   5],
       [ 52, 253, 112],
       [ 14,   1,   3],
       [ 76, 248,  87],
       [233, 212, 184],
       [235, 245,  26],
       [213, 157, 253],
       [ 68, 240,  37],
       [219,  91,  54],
       [129,   9,  51],
       [  0, 191,  20],
       [140,  46, 187],
       [147,   1, 254],
       [ 20, 153, 243],
       [ 46, 160

In [4]:
weightsPath = "./yolov3.weights"
configPath = "./yolov3.cfg" 

In [5]:
net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)
net

<dnn_Net 000001513F504710>

In [6]:
image = cv2.imread('./images/test_image.jpg')
image

array([[[141, 136, 133],
        [141, 136, 133],
        [141, 136, 133],
        ...,
        [169, 165, 170],
        [169, 165, 170],
        [168, 164, 169]],

       [[142, 137, 134],
        [142, 137, 134],
        [142, 137, 134],
        ...,
        [171, 167, 172],
        [170, 166, 171],
        [170, 166, 171]],

       [[142, 137, 134],
        [142, 137, 134],
        [142, 137, 134],
        ...,
        [174, 170, 176],
        [173, 169, 175],
        [173, 169, 175]],

       ...,

       [[ 60,  54,  73],
        [ 64,  58,  77],
        [ 65,  59,  78],
        ...,
        [ 85,  76, 103],
        [ 86,  77, 104],
        [ 87,  78, 105]],

       [[ 65,  56,  76],
        [ 65,  56,  76],
        [ 65,  56,  76],
        ...,
        [ 87,  78, 104],
        [ 87,  78, 104],
        [ 86,  77, 103]],

       [[ 65,  56,  76],
        [ 65,  56,  76],
        [ 65,  56,  76],
        ...,
        [ 87,  78, 104],
        [ 87,  78, 104],
        [ 86,  77, 103]]

In [7]:
(H, W) = image.shape[:2]
ln = net.getLayerNames()
ln = [ln[i[0]- 1] for i in net.getUnconnectedOutLayers()]


blob = cv2.dnn.blobFromImage(image, 1/255.0, (416, 416), swapRB = True, crop = False)
net.setInput(blob)
start = time.time()
layerOutputs = net.forward(ln)
end = time.time()

print("Frame Prediction Time : {:.6f} seconds".format(end - start))

Frame Prediction Time : 1.827865 seconds


In [8]:
boxes = []
confidences = []
classIDs = []

for output in layerOutputs:
    for detection in output:
        scores = detection[5:]
        classID = np.argmax(scores)
        confidence = scores[classID]
        if confidence > 0.5 and classID == 0:
            box = detection[0:4] * np.array([W, H, W, H])
            (centerX, centerY, width, height) = box.astype("int")
            x = int(centerX - (width / 2))
            y = int(centerY - (height / 2))
            boxes.append([x, y, int(width), int(height)])
            confidences.append(float(confidence))
            classIDs.append(classID)
        

In [9]:
idxs = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.3)
ind = []
idxs

array([[ 0],
       [ 3],
       [ 6],
       [ 4],
       [ 7],
       [10],
       [ 5],
       [ 9],
       [ 1],
       [ 8],
       [ 2]], dtype=int32)

In [10]:
for i in range (0, len(classIDs)):
    if(classIDs[i] == 0):
        ind.append(i)
        
ind

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
a = []
b = []

color = (0, 255, 0)
if len(idxs) > 0:
    for i in idxs.flatten():
        (x, y) = (boxes[i][0], boxes[i][1])
        (w, h) = (boxes[i][2], boxes[i][3])
        a.append(x)
        b.append(y)
        cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)

In [12]:
distance = []
nsd = []

for i in range(0, len(a) -1 ):
    for k in range(1, len(a)):
        if (k == i):
            break
        else:
            x_dist = (a[k] - a[i])
            y_dist = (b[k] - b[i])
            d = math.sqrt(x_dist * x_dist  + y_dist * y_dist)
            distance.append(d)
            if (d < 100.0):
                nsd.append(i)
                nsd.append(k)
            nsd = list(dict.fromkeys(nsd))
            
nsd

[3, 1, 4, 2, 6, 7, 5, 8, 9]

In [13]:
color = (0, 0, 255)
text = ""

for i in nsd:
    (x, y) = (boxes[i][0], boxes[i][1])
    (w, h) = (boxes[i][2], boxes[i][3])
    cv2.rectangle(image, (x, y), (x + w, y + h), color, 2)
    text = "Alert"
    cv2.putText(image, text, (x, y-5), cv2.FONT_HERSHEY_SIMPLEX,0.5, color, 2)

In [14]:
cv2.putText(image, text, (x, y-5), cv2.FONT_HERSHEY_SIMPLEX,0.5, color, 2)
cv2.imshow("Social Distancing Detector", image)
cv2.imwrite("output.jpg", image)
cv2.waitKey()

-1